### ISSUE TITLE
Updated (Sept 22) Snipe-IT v6 roadmap

### ISSUE THREAD

**Issue by snipe** [grokability/snipe-it#9834]
Howdy everyone - I hope everyone has been keeping safe during these trying times. I just wanted to give you all a kind of rough roadmap for what the next few months hold for us, the features we're *hoping* to get into v6 of Snipe-IT, and  what that timeline looks like.

**Please make sure you're upgraded to PHP 7.4 or higher before Snipe-IT v6 launches.**

### Timeline

We're hoping to have v6 out by the end of September. <del>We're *hoping* to have this coincide with the release of Laravel 9 LTS, but if for some reason that isn't feasible,</del> Since LTS Laravel v9 won't come out until January, we'll be launching v6 with Laravel v8.4.x and then will drag it forward to Laravel 9 as soon as we can afterwards.

We already have an integration branch in progress on `develop-v6-integration` that's running on Laravel 8.4 and is PHP 8 compatible. 

**We are NOT currently planning on doing much development work on the existing Snipe-IT v5 codebase. New PRs against `develop` will likely not be taken, so please don't submit them. If you have a feature or fix you're interested in working on, you should consider doing them on the integration branch. A LOT will have changed between Snipe-IT v5 and Snipe-IT v6, and it's already going to be merge hell. If a feature is that important, please make it against a fork of `develop` and *also* from a fork of the integration branch. We know it's double the work, but the less awful this merge stuff is, the smoother and faster the v6 rollout will be.**

We will, as always, start to roll out alpha, beta and release candidates as it's ready. You can view a live demo of the v6 branch here: https://demo-v6.snipeitapp.com/

That gets continuously deployed as we push to that integration branch, so it's a good way to get an idea of where we're at at any given point in time. 

### Code Notes

- [ ] No more Vue. I've honestly always disliked it for us, largely because of localization issues and build cycles. I'll  be ripping it out wherever it appears and replacing it with... 
- [ ] Livewire! Livewire is super duper rad and lightning fast and we'll be slowly swapping out some of our clunkier javascript and Vue with Livewire. 
- [ ] JS cleanup (tree-shaking, etc)

Now then, let's get to the good stuff... Here's what we're hoping to add/improve in the v6 line of Snipe-IT:

### Feature Highlights

- [ ] QTY as an option for checkout on consumables, etc
- [ ] Feature to auto-assign licenses for every user
- [ ] "Unlimited seats" for licenses
- [x] G Suite Secure LDAP (client-side certs?)
- [ ] Custom fields for more models (people, licences, etc)
- [ ] Improved UX/UI for checkouts from users page
- [ ] Finer tuning on asset acceptance flow (kiosk mode, storing EULA in the database, etc)
- [ ] Better debugging for SAML
- [x] Re-re-writing the LDAP system to remove AdLdap and improve configuration screens
- [ ] Improving the advanced search in table listings

Here's the roadmap as we currently have it. We're still drilling down the dates of things, and these things can be tricksy in open source, since we kinda never know what outside contirbutors are working on, but also bear in mind that these are *just* the epics, not the actual stories, so you can see there's a ton of work ahead of us. Some of these have already been in progress for a few weeks, some haven't been started yet. Many of these have been weeks or months in planning. 

![roadmap-large](https://user-images.githubusercontent.com/197404/126014157-f6b402c1-cbc5-4274-9763-5577c2c2cf76.png)

If you're interested in working on any of these features, please reach out via GH and discuss with us. We've got the architecture for most of these things pretty solidly mapped out, so we can probably help move things along and make sure you're set up for PR success. 

**And as always, remember - just because YOUR feature might not make it into v6, it's not like we're stopping development when v6 launches. We keep chugging along, and we'll keep adding new features and fixes as we always have.** The only real reason we're even calling it v6 is because there is a PHP version dependency change, an in the spirit of [semver](https://semver.org), we try to do a major version bump when that happens. 

Please do **not** use the replies here to suggest additional things we can "just" squeeze in. This cycle is already pretty aggressive and we'll likely have to trim some stuff out in the coming weeks. But as previously mentioned, just because it doesn't make it into v6 doesn't mean it's not coming soon. 

Be sure to subscribe to our blog at https://grokstar.dev, and check out our newest product, [GoodForms](https://goodforms.com), which offers unlimited email verification (not just validation) and certification for just $10 a month. Also be sure to check out these videos/podcasts if you need to blow some time :)

- [Lightbend Podcast](https://soundcloud.com/lightbend/from-oss-hobby-to-1m-hosted-platform-with-snipe-it)
- [Open Source in Business](https://www.youtube.com/watch?v=aznZZTQwzOk&feature=emb_imp_woyt)
- [2021 Laracon Talk](https://vimeo.com/394206976)

**Comment by jmartins1** [comment]
Please be aware that https://v6.snipe-it-staging.com/login is not available.

Thanks for the great product guys. Can't wait for v6!

**Comment by cb3inco** [comment]
Managing Contracts? Please?

**Comment by snipe** [comment]
@jmartins1 ahh, right, sorry. It’s locked down via AWS security group. I’ll work on getting that opened up for you folks tho.

@cb3inco What did I say? “ Please do not use the replies here to suggest additional things we can "just" squeeze in. This cycle is already pretty aggressive and we'll likely have to trim some stuff out in the coming weeks. But as previously mentioned, just because it doesn't make it into v6 doesn't mean it's not coming soon.”

**Comment by cb3inco** [comment]
Sorry. 😳 I skimmed, I didn't read. 😬

**Comment by PiChG** [comment]
These are wonderfull news!
You're doing outstanding job Guys!

**Comment by PetriAsi** [comment]
Is crowdin already updated with upcoming v6 strings? I would like make sure that Finnish translation stays up to date. :)

**Comment by khnbzkrt** [comment]
Hi, I want to change UI Design of Snipe-IT. Can i make it?

**Comment by snipe** [comment]
Okie dokie folks... so the time draws near. 

We're not going to hit all of our goals on this one, but please do know that the priorities we set here are still valid. 

Projects can be date driven or feature driven, and while we are usually feature driven (which is why we release so often), this one was date driven.

We're getting very close now, and in advance of dealing with the kind of merge hell these big releases tend to be, we're instead going to merge v6 into the `develop` branch today.

This may screw some of you up - I'm sorry about that, genuinely. But by doing so, it gets us closer to being able to release an RC, which will hopefully happen this week. 

What will be on develop (v6) isn't complete yet, we're just trying to ease the blow of the merge conflicts that happen when you're running 3 very disparate branches. 

I'll fill you in more on what we were able to do versus what we couldn't, and also what we thought had to wait until v6 that we already shipped (oops!) in v5 because it made sense to just as soon as I can. 

Thanks for having faith in us. v6 isn't exactly the whole shebang we wanted to launch with, but it's a very necessary step to get us there. 

Stick with us - great things to come!

**Comment by snipe** [comment]
BTW, the demos are down for a spell today, but when they're back up, develop.snipeitapp.com will be v6, demo.snipeitapp.com will be master.

**Comment by snipe** [comment]
Demos are back up:

Current on `master`: https://demo.snipeitapp.com
Current on `develop` (v6): https://develop.snipeitapp.com

username: `admin`
password: `password`

(as usual)

<blockquote><img src="https://demo.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://demo.snipeitapp.com/">Snipe-IT Asset Management Demo</a></strong></div></blockquote>
<blockquote><img src="https://develop.snipeitapp.com/favicon.ico" width="48" align="right"><div><strong><a href="https://develop.snipeitapp.com/">Snipe-IT Asset Management Demo</a></strong></div></blockquote>

**Comment by Elma-mc-Bong** [comment]
is there any news in the topic? I would love to see "QTY as an option for checkout on consumables, etc".

**Comment by thiago-gil** [comment]
> is there any news in the topic? I would love to see "QTY as an option for checkout on consumables, etc".
Looking forward for this feature

**Comment by adagioajanes** [comment]
This is a fantastic roadmap. I'm happy to see there is going to be some love in the license management department. 👍

**Comment by snipe** [comment]
I'm about to tag a release candidate so closing this issue - check the releases page shortly. v6.0.0-RC-1 won't have a lot of what we were hoping to include in v6, but as always, we'll keep chugging along. Some of the planned v6 changes would have resulted in even more delays, and we wanted to get `develop` and `master` back in the same universe at least. The original post above still reflects our priorities.

**Comment by Cube38282** [comment]
Hey, hope you're having a good day! 

I'm really looking forward to the custom fields for people. Is there an ETA on this?

Thanks.

**Comment by uberbrady** [comment]
No, but we've done a little bit of work on extracting the custom fields concept out so that it can be reused. But no ETA yet. After v6 gets released we'll definitely be doing some work on this feature.

**Comment by JanAngelovic** [comment]
> is there any news in the topic? I would love to see "QTY as an option for checkout on consumables, etc".

This is basic feature for asset management software. I am very surprised that it is not still implemented.
